### ISSUE TITLE
[BUG] Errors when running on raspberry pi

### ISSUE THREAD

**Issue by BjornB2** [nicl83/OpenXiino#1]
## Describe the bug

With Python2
```
pi@serialmodem:~/OpenXiino $ python dataserver.py 
  File "dataserver.py", line 11
    def iso8859(string: str) -> bytes:
                      ^
SyntaxError: invalid syntax
```

With Python3
```
pi@serialmodem:~/OpenXiino $ python3 dataserver.py 
Traceback (most recent call last):
  File "/home/pi/OpenXiino/dataserver.py", line 5, in <module>
    from lib.xiino_html_converter import XiinoHTMLParser
  File "/home/pi/OpenXiino/lib/xiino_html_converter.py", line 3, in <module>
    from lib.xiino_image_converter import EBDConverter
  File "/home/pi/OpenXiino/lib/xiino_image_converter.py", line 8, in <module>
    import lib.scanline as scanline
  File "/home/pi/OpenXiino/lib/scanline.py", line 10, in <module>
    prev_line: bytes | None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
Installed the requirements, installed libopenjp2-7. 
What am I doing wrong? Thanks for your help!

## Device Info
- Device name: Raspberry Pi 3B
- OS version: Raspbian Lite

## Additional context
I am making a serial modem for vintage devices and wanted to add OpenXiino to the server. 
https://www.bjornsblog.nl/general/how-to-connect-your-psion-to-the-internet-in-2024/

**Comment by nicl83** [comment]
OpenXiino will not run under Python2, it requires Python3.

The `TypeError` that occurs in Python3 is caused by running OpenXiino on an older version of Python3 - `bytes | None` is a [union type](https://peps.python.org/pep-0604/), which was added in Python 3.10. OpenXiino will not run on Python 3.9 or earlier, so if you're running Python 3.9 or earlier, you'll need to install a newer version of Python to run OpenXiino.

Thanks for letting me know about this - I'll update the README to mention that Python 3.10 or newer is required.
